---
name: Save licenses report

on:
  schedule:
    - cron: '30 6 7 */2 *' # 6:30 am UTC: 1:30 am EST on 7th day of every 2nd month
  workflow_dispatch:

concurrency:
  group: licenses-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  license_report:
    name: License report
    uses: wealthsimple/github-workflows/.github/workflows/ruby_license_report.yml@v1
    secrets: inherit
